// Code generated by makeservice. DO NOT EDIT.

// Package grouprenderingcontrol is a generated GroupRenderingControl package.
package grouprenderingcontrol

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io/ioutil"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:GroupRenderingControl:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

type GroupMute bool
type GroupVolume uint16
type GroupVolumeChangeable bool

type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL

	GroupMute             *GroupMute
	GroupVolume           *GroupVolume
	GroupVolumeChangeable *GroupVolumeChangeable

	location *url.URL
	client   *http.Client
}

func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaRenderer/GroupRenderingControl/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaRenderer/GroupRenderingControl/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

func (s *Service) Location() *url.URL {
	return s.location
}

func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                xml.Name                    `xml:"s:Body"`
	GetGroupMute           *GetGroupMuteArgs           `xml:"u:GetGroupMute,omitempty"`
	SetGroupMute           *SetGroupMuteArgs           `xml:"u:SetGroupMute,omitempty"`
	GetGroupVolume         *GetGroupVolumeArgs         `xml:"u:GetGroupVolume,omitempty"`
	SetGroupVolume         *SetGroupVolumeArgs         `xml:"u:SetGroupVolume,omitempty"`
	SetRelativeGroupVolume *SetRelativeGroupVolumeArgs `xml:"u:SetRelativeGroupVolume,omitempty"`
	SnapshotGroupVolume    *SnapshotGroupVolumeArgs    `xml:"u:SnapshotGroupVolume,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                xml.Name                        `xml:"Body"`
	GetGroupMute           *GetGroupMuteResponse           `xml:"GetGroupMuteResponse,omitempty"`
	SetGroupMute           *SetGroupMuteResponse           `xml:"SetGroupMuteResponse,omitempty"`
	GetGroupVolume         *GetGroupVolumeResponse         `xml:"GetGroupVolumeResponse,omitempty"`
	SetGroupVolume         *SetGroupVolumeResponse         `xml:"SetGroupVolumeResponse,omitempty"`
	SetRelativeGroupVolume *SetRelativeGroupVolumeResponse `xml:"SetRelativeGroupVolumeResponse,omitempty"`
	SnapshotGroupVolume    *SnapshotGroupVolumeResponse    `xml:"SnapshotGroupVolumeResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

type GetGroupMuteArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetGroupMuteResponse struct {
	CurrentMute bool `xml:"CurrentMute"`
}

func (s *Service) GetGroupMute(args *GetGroupMuteArgs) (*GetGroupMuteResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetGroupMute",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetGroupMute: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetGroupMute == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.GetGroupMute()`)
	}

	return r.Body.GetGroupMute, nil
}

type SetGroupMuteArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	InstanceID  uint32 `xml:"InstanceID"`
	DesiredMute bool   `xml:"DesiredMute"`
}
type SetGroupMuteResponse struct {
}

func (s *Service) SetGroupMute(args *SetGroupMuteArgs) (*SetGroupMuteResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetGroupMute",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetGroupMute: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetGroupMute == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.SetGroupMute()`)
	}

	return r.Body.SetGroupMute, nil
}

type GetGroupVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetGroupVolumeResponse struct {
	CurrentVolume uint16 `xml:"CurrentVolume"`
}

func (s *Service) GetGroupVolume(args *GetGroupVolumeArgs) (*GetGroupVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetGroupVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetGroupVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetGroupVolume == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.GetGroupVolume()`)
	}

	return r.Body.GetGroupVolume, nil
}

type SetGroupVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	// Allowed Range: 0 -> 100 step: 1
	DesiredVolume uint16 `xml:"DesiredVolume"`
}
type SetGroupVolumeResponse struct {
}

func (s *Service) SetGroupVolume(args *SetGroupVolumeArgs) (*SetGroupVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetGroupVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetGroupVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetGroupVolume == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.SetGroupVolume()`)
	}

	return r.Body.SetGroupVolume, nil
}

type SetRelativeGroupVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Adjustment int32  `xml:"Adjustment"`
}
type SetRelativeGroupVolumeResponse struct {
	NewVolume uint16 `xml:"NewVolume"`
}

func (s *Service) SetRelativeGroupVolume(args *SetRelativeGroupVolumeArgs) (*SetRelativeGroupVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetRelativeGroupVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetRelativeGroupVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetRelativeGroupVolume == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.SetRelativeGroupVolume()`)
	}

	return r.Body.SetRelativeGroupVolume, nil
}

type SnapshotGroupVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type SnapshotGroupVolumeResponse struct {
}

func (s *Service) SnapshotGroupVolume(args *SnapshotGroupVolumeArgs) (*SnapshotGroupVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SnapshotGroupVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SnapshotGroupVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SnapshotGroupVolume == nil {
		return nil, errors.New(`unexpected response from service calling grouprenderingcontrol.SnapshotGroupVolume()`)
	}

	return r.Body.SnapshotGroupVolume, nil
}

type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}
type Property struct {
	XMLName               xml.Name               `xml:"property"`
	GroupMute             *GroupMute             `xml:"GroupMute"`
	GroupVolume           *GroupVolume           `xml:"GroupVolume"`
	GroupVolumeChangeable *GroupVolumeChangeable `xml:"GroupVolumeChangeable"`
}

func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}
	err := xml.Unmarshal(body, &evt)
	if err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.GroupMute != nil:
			zp.GroupMute = prop.GroupMute
			events = append(events, *prop.GroupMute)
		case prop.GroupVolume != nil:
			zp.GroupVolume = prop.GroupVolume
			events = append(events, *prop.GroupVolume)
		case prop.GroupVolumeChangeable != nil:
			zp.GroupVolumeChangeable = prop.GroupVolumeChangeable
			events = append(events, *prop.GroupVolumeChangeable)
		}
	}
	return events
}
