// Code generated by makeservice. DO NOT EDIT.

// Package avtransport is a generated AVTransport package.
package avtransport

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io/ioutil"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:AVTransport:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

type LastChange string

type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL

	LastChange *LastChange

	location *url.URL
	client   *http.Client
}

func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaRenderer/AVTransport/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaRenderer/AVTransport/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

func (s *Service) Location() *url.URL {
	return s.location
}

func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                            xml.Name                                `xml:"s:Body"`
	SetAVTransportURI                  *SetAVTransportURIArgs                  `xml:"u:SetAVTransportURI,omitempty"`
	SetNextAVTransportURI              *SetNextAVTransportURIArgs              `xml:"u:SetNextAVTransportURI,omitempty"`
	AddURIToQueue                      *AddURIToQueueArgs                      `xml:"u:AddURIToQueue,omitempty"`
	AddMultipleURIsToQueue             *AddMultipleURIsToQueueArgs             `xml:"u:AddMultipleURIsToQueue,omitempty"`
	ReorderTracksInQueue               *ReorderTracksInQueueArgs               `xml:"u:ReorderTracksInQueue,omitempty"`
	RemoveTrackFromQueue               *RemoveTrackFromQueueArgs               `xml:"u:RemoveTrackFromQueue,omitempty"`
	RemoveTrackRangeFromQueue          *RemoveTrackRangeFromQueueArgs          `xml:"u:RemoveTrackRangeFromQueue,omitempty"`
	RemoveAllTracksFromQueue           *RemoveAllTracksFromQueueArgs           `xml:"u:RemoveAllTracksFromQueue,omitempty"`
	SaveQueue                          *SaveQueueArgs                          `xml:"u:SaveQueue,omitempty"`
	BackupQueue                        *BackupQueueArgs                        `xml:"u:BackupQueue,omitempty"`
	CreateSavedQueue                   *CreateSavedQueueArgs                   `xml:"u:CreateSavedQueue,omitempty"`
	AddURIToSavedQueue                 *AddURIToSavedQueueArgs                 `xml:"u:AddURIToSavedQueue,omitempty"`
	ReorderTracksInSavedQueue          *ReorderTracksInSavedQueueArgs          `xml:"u:ReorderTracksInSavedQueue,omitempty"`
	GetMediaInfo                       *GetMediaInfoArgs                       `xml:"u:GetMediaInfo,omitempty"`
	GetTransportInfo                   *GetTransportInfoArgs                   `xml:"u:GetTransportInfo,omitempty"`
	GetPositionInfo                    *GetPositionInfoArgs                    `xml:"u:GetPositionInfo,omitempty"`
	GetDeviceCapabilities              *GetDeviceCapabilitiesArgs              `xml:"u:GetDeviceCapabilities,omitempty"`
	GetTransportSettings               *GetTransportSettingsArgs               `xml:"u:GetTransportSettings,omitempty"`
	GetCrossfadeMode                   *GetCrossfadeModeArgs                   `xml:"u:GetCrossfadeMode,omitempty"`
	Stop                               *StopArgs                               `xml:"u:Stop,omitempty"`
	Play                               *PlayArgs                               `xml:"u:Play,omitempty"`
	Pause                              *PauseArgs                              `xml:"u:Pause,omitempty"`
	Seek                               *SeekArgs                               `xml:"u:Seek,omitempty"`
	Next                               *NextArgs                               `xml:"u:Next,omitempty"`
	Previous                           *PreviousArgs                           `xml:"u:Previous,omitempty"`
	SetPlayMode                        *SetPlayModeArgs                        `xml:"u:SetPlayMode,omitempty"`
	SetCrossfadeMode                   *SetCrossfadeModeArgs                   `xml:"u:SetCrossfadeMode,omitempty"`
	NotifyDeletedURI                   *NotifyDeletedURIArgs                   `xml:"u:NotifyDeletedURI,omitempty"`
	GetCurrentTransportActions         *GetCurrentTransportActionsArgs         `xml:"u:GetCurrentTransportActions,omitempty"`
	BecomeCoordinatorOfStandaloneGroup *BecomeCoordinatorOfStandaloneGroupArgs `xml:"u:BecomeCoordinatorOfStandaloneGroup,omitempty"`
	DelegateGroupCoordinationTo        *DelegateGroupCoordinationToArgs        `xml:"u:DelegateGroupCoordinationTo,omitempty"`
	BecomeGroupCoordinator             *BecomeGroupCoordinatorArgs             `xml:"u:BecomeGroupCoordinator,omitempty"`
	BecomeGroupCoordinatorAndSource    *BecomeGroupCoordinatorAndSourceArgs    `xml:"u:BecomeGroupCoordinatorAndSource,omitempty"`
	ChangeCoordinator                  *ChangeCoordinatorArgs                  `xml:"u:ChangeCoordinator,omitempty"`
	ChangeTransportSettings            *ChangeTransportSettingsArgs            `xml:"u:ChangeTransportSettings,omitempty"`
	ConfigureSleepTimer                *ConfigureSleepTimerArgs                `xml:"u:ConfigureSleepTimer,omitempty"`
	GetRemainingSleepTimerDuration     *GetRemainingSleepTimerDurationArgs     `xml:"u:GetRemainingSleepTimerDuration,omitempty"`
	RunAlarm                           *RunAlarmArgs                           `xml:"u:RunAlarm,omitempty"`
	StartAutoplay                      *StartAutoplayArgs                      `xml:"u:StartAutoplay,omitempty"`
	GetRunningAlarmProperties          *GetRunningAlarmPropertiesArgs          `xml:"u:GetRunningAlarmProperties,omitempty"`
	SnoozeAlarm                        *SnoozeAlarmArgs                        `xml:"u:SnoozeAlarm,omitempty"`
	EndDirectControlSession            *EndDirectControlSessionArgs            `xml:"u:EndDirectControlSession,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                            xml.Name                                    `xml:"Body"`
	SetAVTransportURI                  *SetAVTransportURIResponse                  `xml:"SetAVTransportURIResponse,omitempty"`
	SetNextAVTransportURI              *SetNextAVTransportURIResponse              `xml:"SetNextAVTransportURIResponse,omitempty"`
	AddURIToQueue                      *AddURIToQueueResponse                      `xml:"AddURIToQueueResponse,omitempty"`
	AddMultipleURIsToQueue             *AddMultipleURIsToQueueResponse             `xml:"AddMultipleURIsToQueueResponse,omitempty"`
	ReorderTracksInQueue               *ReorderTracksInQueueResponse               `xml:"ReorderTracksInQueueResponse,omitempty"`
	RemoveTrackFromQueue               *RemoveTrackFromQueueResponse               `xml:"RemoveTrackFromQueueResponse,omitempty"`
	RemoveTrackRangeFromQueue          *RemoveTrackRangeFromQueueResponse          `xml:"RemoveTrackRangeFromQueueResponse,omitempty"`
	RemoveAllTracksFromQueue           *RemoveAllTracksFromQueueResponse           `xml:"RemoveAllTracksFromQueueResponse,omitempty"`
	SaveQueue                          *SaveQueueResponse                          `xml:"SaveQueueResponse,omitempty"`
	BackupQueue                        *BackupQueueResponse                        `xml:"BackupQueueResponse,omitempty"`
	CreateSavedQueue                   *CreateSavedQueueResponse                   `xml:"CreateSavedQueueResponse,omitempty"`
	AddURIToSavedQueue                 *AddURIToSavedQueueResponse                 `xml:"AddURIToSavedQueueResponse,omitempty"`
	ReorderTracksInSavedQueue          *ReorderTracksInSavedQueueResponse          `xml:"ReorderTracksInSavedQueueResponse,omitempty"`
	GetMediaInfo                       *GetMediaInfoResponse                       `xml:"GetMediaInfoResponse,omitempty"`
	GetTransportInfo                   *GetTransportInfoResponse                   `xml:"GetTransportInfoResponse,omitempty"`
	GetPositionInfo                    *GetPositionInfoResponse                    `xml:"GetPositionInfoResponse,omitempty"`
	GetDeviceCapabilities              *GetDeviceCapabilitiesResponse              `xml:"GetDeviceCapabilitiesResponse,omitempty"`
	GetTransportSettings               *GetTransportSettingsResponse               `xml:"GetTransportSettingsResponse,omitempty"`
	GetCrossfadeMode                   *GetCrossfadeModeResponse                   `xml:"GetCrossfadeModeResponse,omitempty"`
	Stop                               *StopResponse                               `xml:"StopResponse,omitempty"`
	Play                               *PlayResponse                               `xml:"PlayResponse,omitempty"`
	Pause                              *PauseResponse                              `xml:"PauseResponse,omitempty"`
	Seek                               *SeekResponse                               `xml:"SeekResponse,omitempty"`
	Next                               *NextResponse                               `xml:"NextResponse,omitempty"`
	Previous                           *PreviousResponse                           `xml:"PreviousResponse,omitempty"`
	SetPlayMode                        *SetPlayModeResponse                        `xml:"SetPlayModeResponse,omitempty"`
	SetCrossfadeMode                   *SetCrossfadeModeResponse                   `xml:"SetCrossfadeModeResponse,omitempty"`
	NotifyDeletedURI                   *NotifyDeletedURIResponse                   `xml:"NotifyDeletedURIResponse,omitempty"`
	GetCurrentTransportActions         *GetCurrentTransportActionsResponse         `xml:"GetCurrentTransportActionsResponse,omitempty"`
	BecomeCoordinatorOfStandaloneGroup *BecomeCoordinatorOfStandaloneGroupResponse `xml:"BecomeCoordinatorOfStandaloneGroupResponse,omitempty"`
	DelegateGroupCoordinationTo        *DelegateGroupCoordinationToResponse        `xml:"DelegateGroupCoordinationToResponse,omitempty"`
	BecomeGroupCoordinator             *BecomeGroupCoordinatorResponse             `xml:"BecomeGroupCoordinatorResponse,omitempty"`
	BecomeGroupCoordinatorAndSource    *BecomeGroupCoordinatorAndSourceResponse    `xml:"BecomeGroupCoordinatorAndSourceResponse,omitempty"`
	ChangeCoordinator                  *ChangeCoordinatorResponse                  `xml:"ChangeCoordinatorResponse,omitempty"`
	ChangeTransportSettings            *ChangeTransportSettingsResponse            `xml:"ChangeTransportSettingsResponse,omitempty"`
	ConfigureSleepTimer                *ConfigureSleepTimerResponse                `xml:"ConfigureSleepTimerResponse,omitempty"`
	GetRemainingSleepTimerDuration     *GetRemainingSleepTimerDurationResponse     `xml:"GetRemainingSleepTimerDurationResponse,omitempty"`
	RunAlarm                           *RunAlarmResponse                           `xml:"RunAlarmResponse,omitempty"`
	StartAutoplay                      *StartAutoplayResponse                      `xml:"StartAutoplayResponse,omitempty"`
	GetRunningAlarmProperties          *GetRunningAlarmPropertiesResponse          `xml:"GetRunningAlarmPropertiesResponse,omitempty"`
	SnoozeAlarm                        *SnoozeAlarmResponse                        `xml:"SnoozeAlarmResponse,omitempty"`
	EndDirectControlSession            *EndDirectControlSessionResponse            `xml:"EndDirectControlSessionResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

type SetAVTransportURIArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	InstanceID         uint32 `xml:"InstanceID"`
	CurrentURI         string `xml:"CurrentURI"`
	CurrentURIMetaData string `xml:"CurrentURIMetaData"`
}
type SetAVTransportURIResponse struct {
}

func (s *Service) SetAVTransportURI(args *SetAVTransportURIArgs) (*SetAVTransportURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetAVTransportURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetAVTransportURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetAVTransportURI == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SetAVTransportURI()`)
	}

	return r.Body.SetAVTransportURI, nil
}

type SetNextAVTransportURIArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	NextURI         string `xml:"NextURI"`
	NextURIMetaData string `xml:"NextURIMetaData"`
}
type SetNextAVTransportURIResponse struct {
}

func (s *Service) SetNextAVTransportURI(args *SetNextAVTransportURIArgs) (*SetNextAVTransportURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetNextAVTransportURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetNextAVTransportURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetNextAVTransportURI == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SetNextAVTransportURI()`)
	}

	return r.Body.SetNextAVTransportURI, nil
}

type AddURIToQueueArgs struct {
	Xmlns                           string `xml:"xmlns:u,attr"`
	InstanceID                      uint32 `xml:"InstanceID"`
	EnqueuedURI                     string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData             string `xml:"EnqueuedURIMetaData"`
	DesiredFirstTrackNumberEnqueued uint32 `xml:"DesiredFirstTrackNumberEnqueued"`
	EnqueueAsNext                   bool   `xml:"EnqueueAsNext"`
}
type AddURIToQueueResponse struct {
	FirstTrackNumberEnqueued uint32 `xml:"FirstTrackNumberEnqueued"`
	NumTracksAdded           uint32 `xml:"NumTracksAdded"`
	NewQueueLength           uint32 `xml:"NewQueueLength"`
}

func (s *Service) AddURIToQueue(args *AddURIToQueueArgs) (*AddURIToQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddURIToQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddURIToQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddURIToQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.AddURIToQueue()`)
	}

	return r.Body.AddURIToQueue, nil
}

type AddMultipleURIsToQueueArgs struct {
	Xmlns                           string `xml:"xmlns:u,attr"`
	InstanceID                      uint32 `xml:"InstanceID"`
	UpdateID                        uint32 `xml:"UpdateID"`
	NumberOfURIs                    uint32 `xml:"NumberOfURIs"`
	EnqueuedURIs                    string `xml:"EnqueuedURIs"`
	EnqueuedURIsMetaData            string `xml:"EnqueuedURIsMetaData"`
	ContainerURI                    string `xml:"ContainerURI"`
	ContainerMetaData               string `xml:"ContainerMetaData"`
	DesiredFirstTrackNumberEnqueued uint32 `xml:"DesiredFirstTrackNumberEnqueued"`
	EnqueueAsNext                   bool   `xml:"EnqueueAsNext"`
}
type AddMultipleURIsToQueueResponse struct {
	FirstTrackNumberEnqueued uint32 `xml:"FirstTrackNumberEnqueued"`
	NumTracksAdded           uint32 `xml:"NumTracksAdded"`
	NewQueueLength           uint32 `xml:"NewQueueLength"`
	NewUpdateID              uint32 `xml:"NewUpdateID"`
}

func (s *Service) AddMultipleURIsToQueue(args *AddMultipleURIsToQueueArgs) (*AddMultipleURIsToQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddMultipleURIsToQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddMultipleURIsToQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddMultipleURIsToQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.AddMultipleURIsToQueue()`)
	}

	return r.Body.AddMultipleURIsToQueue, nil
}

type ReorderTracksInQueueArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	StartingIndex  uint32 `xml:"StartingIndex"`
	NumberOfTracks uint32 `xml:"NumberOfTracks"`
	InsertBefore   uint32 `xml:"InsertBefore"`
	UpdateID       uint32 `xml:"UpdateID"`
}
type ReorderTracksInQueueResponse struct {
}

func (s *Service) ReorderTracksInQueue(args *ReorderTracksInQueueArgs) (*ReorderTracksInQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ReorderTracksInQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ReorderTracksInQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ReorderTracksInQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.ReorderTracksInQueue()`)
	}

	return r.Body.ReorderTracksInQueue, nil
}

type RemoveTrackFromQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	ObjectID   string `xml:"ObjectID"`
	UpdateID   uint32 `xml:"UpdateID"`
}
type RemoveTrackFromQueueResponse struct {
}

func (s *Service) RemoveTrackFromQueue(args *RemoveTrackFromQueueArgs) (*RemoveTrackFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveTrackFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveTrackFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveTrackFromQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.RemoveTrackFromQueue()`)
	}

	return r.Body.RemoveTrackFromQueue, nil
}

type RemoveTrackRangeFromQueueArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	UpdateID       uint32 `xml:"UpdateID"`
	StartingIndex  uint32 `xml:"StartingIndex"`
	NumberOfTracks uint32 `xml:"NumberOfTracks"`
}
type RemoveTrackRangeFromQueueResponse struct {
	NewUpdateID uint32 `xml:"NewUpdateID"`
}

func (s *Service) RemoveTrackRangeFromQueue(args *RemoveTrackRangeFromQueueArgs) (*RemoveTrackRangeFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveTrackRangeFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveTrackRangeFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveTrackRangeFromQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.RemoveTrackRangeFromQueue()`)
	}

	return r.Body.RemoveTrackRangeFromQueue, nil
}

type RemoveAllTracksFromQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type RemoveAllTracksFromQueueResponse struct {
}

func (s *Service) RemoveAllTracksFromQueue(args *RemoveAllTracksFromQueueArgs) (*RemoveAllTracksFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveAllTracksFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveAllTracksFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveAllTracksFromQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.RemoveAllTracksFromQueue()`)
	}

	return r.Body.RemoveAllTracksFromQueue, nil
}

type SaveQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Title      string `xml:"Title"`
	ObjectID   string `xml:"ObjectID"`
}
type SaveQueueResponse struct {
	AssignedObjectID string `xml:"AssignedObjectID"`
}

func (s *Service) SaveQueue(args *SaveQueueArgs) (*SaveQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SaveQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SaveQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SaveQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SaveQueue()`)
	}

	return r.Body.SaveQueue, nil
}

type BackupQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type BackupQueueResponse struct {
}

func (s *Service) BackupQueue(args *BackupQueueArgs) (*BackupQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BackupQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BackupQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BackupQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.BackupQueue()`)
	}

	return r.Body.BackupQueue, nil
}

type CreateSavedQueueArgs struct {
	Xmlns               string `xml:"xmlns:u,attr"`
	InstanceID          uint32 `xml:"InstanceID"`
	Title               string `xml:"Title"`
	EnqueuedURI         string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData string `xml:"EnqueuedURIMetaData"`
}
type CreateSavedQueueResponse struct {
	NumTracksAdded   uint32 `xml:"NumTracksAdded"`
	NewQueueLength   uint32 `xml:"NewQueueLength"`
	AssignedObjectID string `xml:"AssignedObjectID"`
	NewUpdateID      uint32 `xml:"NewUpdateID"`
}

func (s *Service) CreateSavedQueue(args *CreateSavedQueueArgs) (*CreateSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("CreateSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{CreateSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.CreateSavedQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.CreateSavedQueue()`)
	}

	return r.Body.CreateSavedQueue, nil
}

type AddURIToSavedQueueArgs struct {
	Xmlns               string `xml:"xmlns:u,attr"`
	InstanceID          uint32 `xml:"InstanceID"`
	ObjectID            string `xml:"ObjectID"`
	UpdateID            uint32 `xml:"UpdateID"`
	EnqueuedURI         string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData string `xml:"EnqueuedURIMetaData"`
	AddAtIndex          uint32 `xml:"AddAtIndex"`
}
type AddURIToSavedQueueResponse struct {
	NumTracksAdded uint32 `xml:"NumTracksAdded"`
	NewQueueLength uint32 `xml:"NewQueueLength"`
	NewUpdateID    uint32 `xml:"NewUpdateID"`
}

func (s *Service) AddURIToSavedQueue(args *AddURIToSavedQueueArgs) (*AddURIToSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddURIToSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddURIToSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddURIToSavedQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.AddURIToSavedQueue()`)
	}

	return r.Body.AddURIToSavedQueue, nil
}

type ReorderTracksInSavedQueueArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	ObjectID        string `xml:"ObjectID"`
	UpdateID        uint32 `xml:"UpdateID"`
	TrackList       string `xml:"TrackList"`
	NewPositionList string `xml:"NewPositionList"`
}
type ReorderTracksInSavedQueueResponse struct {
	QueueLengthChange int32  `xml:"QueueLengthChange"`
	NewQueueLength    uint32 `xml:"NewQueueLength"`
	NewUpdateID       uint32 `xml:"NewUpdateID"`
}

func (s *Service) ReorderTracksInSavedQueue(args *ReorderTracksInSavedQueueArgs) (*ReorderTracksInSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ReorderTracksInSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ReorderTracksInSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ReorderTracksInSavedQueue == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.ReorderTracksInSavedQueue()`)
	}

	return r.Body.ReorderTracksInSavedQueue, nil
}

type GetMediaInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetMediaInfoResponse struct {
	NrTracks           uint32 `xml:"NrTracks"`
	MediaDuration      string `xml:"MediaDuration"`
	CurrentURI         string `xml:"CurrentURI"`
	CurrentURIMetaData string `xml:"CurrentURIMetaData"`
	NextURI            string `xml:"NextURI"`
	NextURIMetaData    string `xml:"NextURIMetaData"`
	PlayMedium         string `xml:"PlayMedium"`
	RecordMedium       string `xml:"RecordMedium"`
	WriteStatus        string `xml:"WriteStatus"`
}

func (s *Service) GetMediaInfo(args *GetMediaInfoArgs) (*GetMediaInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetMediaInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetMediaInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetMediaInfo == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetMediaInfo()`)
	}

	return r.Body.GetMediaInfo, nil
}

type GetTransportInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetTransportInfoResponse struct {
	CurrentTransportState  string `xml:"CurrentTransportState"`
	CurrentTransportStatus string `xml:"CurrentTransportStatus"`
	CurrentSpeed           string `xml:"CurrentSpeed"`
}

func (s *Service) GetTransportInfo(args *GetTransportInfoArgs) (*GetTransportInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTransportInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTransportInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTransportInfo == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetTransportInfo()`)
	}

	return r.Body.GetTransportInfo, nil
}

type GetPositionInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetPositionInfoResponse struct {
	Track         uint32 `xml:"Track"`
	TrackDuration string `xml:"TrackDuration"`
	TrackMetaData string `xml:"TrackMetaData"`
	TrackURI      string `xml:"TrackURI"`
	RelTime       string `xml:"RelTime"`
	AbsTime       string `xml:"AbsTime"`
	RelCount      int32  `xml:"RelCount"`
	AbsCount      int32  `xml:"AbsCount"`
}

func (s *Service) GetPositionInfo(args *GetPositionInfoArgs) (*GetPositionInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetPositionInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetPositionInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetPositionInfo == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetPositionInfo()`)
	}

	return r.Body.GetPositionInfo, nil
}

type GetDeviceCapabilitiesArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetDeviceCapabilitiesResponse struct {
	PlayMedia       string `xml:"PlayMedia"`
	RecMedia        string `xml:"RecMedia"`
	RecQualityModes string `xml:"RecQualityModes"`
}

func (s *Service) GetDeviceCapabilities(args *GetDeviceCapabilitiesArgs) (*GetDeviceCapabilitiesResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetDeviceCapabilities",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetDeviceCapabilities: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetDeviceCapabilities == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetDeviceCapabilities()`)
	}

	return r.Body.GetDeviceCapabilities, nil
}

type GetTransportSettingsArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetTransportSettingsResponse struct {
	PlayMode       string `xml:"PlayMode"`
	RecQualityMode string `xml:"RecQualityMode"`
}

func (s *Service) GetTransportSettings(args *GetTransportSettingsArgs) (*GetTransportSettingsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTransportSettings",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTransportSettings: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTransportSettings == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetTransportSettings()`)
	}

	return r.Body.GetTransportSettings, nil
}

type GetCrossfadeModeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetCrossfadeModeResponse struct {
	CrossfadeMode bool `xml:"CrossfadeMode"`
}

func (s *Service) GetCrossfadeMode(args *GetCrossfadeModeArgs) (*GetCrossfadeModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCrossfadeMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCrossfadeMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCrossfadeMode == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetCrossfadeMode()`)
	}

	return r.Body.GetCrossfadeMode, nil
}

type StopArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type StopResponse struct {
}

func (s *Service) Stop(args *StopArgs) (*StopResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Stop",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Stop: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Stop == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Stop()`)
	}

	return r.Body.Stop, nil
}

type PlayArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	// Allowed Value: 1
	Speed string `xml:"Speed"`
}
type PlayResponse struct {
}

func (s *Service) Play(args *PlayArgs) (*PlayResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Play",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Play: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Play == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Play()`)
	}

	return r.Body.Play, nil
}

type PauseArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type PauseResponse struct {
}

func (s *Service) Pause(args *PauseArgs) (*PauseResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Pause",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Pause: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Pause == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Pause()`)
	}

	return r.Body.Pause, nil
}

type SeekArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	// Allowed Value: TRACK_NR
	// Allowed Value: REL_TIME
	// Allowed Value: TIME_DELTA
	Unit   string `xml:"Unit"`
	Target string `xml:"Target"`
}
type SeekResponse struct {
}

func (s *Service) Seek(args *SeekArgs) (*SeekResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Seek",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Seek: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Seek == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Seek()`)
	}

	return r.Body.Seek, nil
}

type NextArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type NextResponse struct {
}

func (s *Service) Next(args *NextArgs) (*NextResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Next",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Next: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Next == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Next()`)
	}

	return r.Body.Next, nil
}

type PreviousArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type PreviousResponse struct {
}

func (s *Service) Previous(args *PreviousArgs) (*PreviousResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Previous",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Previous: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Previous == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.Previous()`)
	}

	return r.Body.Previous, nil
}

type SetPlayModeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	// Allowed Value: NORMAL
	// Allowed Value: REPEAT_ALL
	// Allowed Value: REPEAT_ONE
	// Allowed Value: SHUFFLE_NOREPEAT
	// Allowed Value: SHUFFLE
	// Allowed Value: SHUFFLE_REPEAT_ONE
	NewPlayMode string `xml:"NewPlayMode"`
}
type SetPlayModeResponse struct {
}

func (s *Service) SetPlayMode(args *SetPlayModeArgs) (*SetPlayModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetPlayMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetPlayMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetPlayMode == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SetPlayMode()`)
	}

	return r.Body.SetPlayMode, nil
}

type SetCrossfadeModeArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	CrossfadeMode bool   `xml:"CrossfadeMode"`
}
type SetCrossfadeModeResponse struct {
}

func (s *Service) SetCrossfadeMode(args *SetCrossfadeModeArgs) (*SetCrossfadeModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetCrossfadeMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetCrossfadeMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetCrossfadeMode == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SetCrossfadeMode()`)
	}

	return r.Body.SetCrossfadeMode, nil
}

type NotifyDeletedURIArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	DeletedURI string `xml:"DeletedURI"`
}
type NotifyDeletedURIResponse struct {
}

func (s *Service) NotifyDeletedURI(args *NotifyDeletedURIArgs) (*NotifyDeletedURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("NotifyDeletedURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{NotifyDeletedURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.NotifyDeletedURI == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.NotifyDeletedURI()`)
	}

	return r.Body.NotifyDeletedURI, nil
}

type GetCurrentTransportActionsArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetCurrentTransportActionsResponse struct {
	Actions string `xml:"Actions"`
}

func (s *Service) GetCurrentTransportActions(args *GetCurrentTransportActionsArgs) (*GetCurrentTransportActionsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCurrentTransportActions",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCurrentTransportActions: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCurrentTransportActions == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetCurrentTransportActions()`)
	}

	return r.Body.GetCurrentTransportActions, nil
}

type BecomeCoordinatorOfStandaloneGroupArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type BecomeCoordinatorOfStandaloneGroupResponse struct {
	DelegatedGroupCoordinatorID string `xml:"DelegatedGroupCoordinatorID"`
	NewGroupID                  string `xml:"NewGroupID"`
}

func (s *Service) BecomeCoordinatorOfStandaloneGroup(args *BecomeCoordinatorOfStandaloneGroupArgs) (*BecomeCoordinatorOfStandaloneGroupResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeCoordinatorOfStandaloneGroup",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeCoordinatorOfStandaloneGroup: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeCoordinatorOfStandaloneGroup == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.BecomeCoordinatorOfStandaloneGroup()`)
	}

	return r.Body.BecomeCoordinatorOfStandaloneGroup, nil
}

type DelegateGroupCoordinationToArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	NewCoordinator string `xml:"NewCoordinator"`
	RejoinGroup    bool   `xml:"RejoinGroup"`
}
type DelegateGroupCoordinationToResponse struct {
}

func (s *Service) DelegateGroupCoordinationTo(args *DelegateGroupCoordinationToArgs) (*DelegateGroupCoordinationToResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("DelegateGroupCoordinationTo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{DelegateGroupCoordinationTo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.DelegateGroupCoordinationTo == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.DelegateGroupCoordinationTo()`)
	}

	return r.Body.DelegateGroupCoordinationTo, nil
}

type BecomeGroupCoordinatorArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	CurrentGroupID        string `xml:"CurrentGroupID"`
	OtherMembers          string `xml:"OtherMembers"`
	TransportSettings     string `xml:"TransportSettings"`
	CurrentURI            string `xml:"CurrentURI"`
	CurrentURIMetaData    string `xml:"CurrentURIMetaData"`
	SleepTimerState       string `xml:"SleepTimerState"`
	AlarmState            string `xml:"AlarmState"`
	StreamRestartState    string `xml:"StreamRestartState"`
	CurrentQueueTrackList string `xml:"CurrentQueueTrackList"`
	CurrentVLIState       string `xml:"CurrentVLIState"`
}
type BecomeGroupCoordinatorResponse struct {
}

func (s *Service) BecomeGroupCoordinator(args *BecomeGroupCoordinatorArgs) (*BecomeGroupCoordinatorResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeGroupCoordinator",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeGroupCoordinator: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeGroupCoordinator == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.BecomeGroupCoordinator()`)
	}

	return r.Body.BecomeGroupCoordinator, nil
}

type BecomeGroupCoordinatorAndSourceArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	CurrentGroupID        string `xml:"CurrentGroupID"`
	OtherMembers          string `xml:"OtherMembers"`
	CurrentURI            string `xml:"CurrentURI"`
	CurrentURIMetaData    string `xml:"CurrentURIMetaData"`
	SleepTimerState       string `xml:"SleepTimerState"`
	AlarmState            string `xml:"AlarmState"`
	StreamRestartState    string `xml:"StreamRestartState"`
	CurrentAVTTrackList   string `xml:"CurrentAVTTrackList"`
	CurrentQueueTrackList string `xml:"CurrentQueueTrackList"`
	CurrentSourceState    string `xml:"CurrentSourceState"`
	ResumePlayback        bool   `xml:"ResumePlayback"`
}
type BecomeGroupCoordinatorAndSourceResponse struct {
}

func (s *Service) BecomeGroupCoordinatorAndSource(args *BecomeGroupCoordinatorAndSourceArgs) (*BecomeGroupCoordinatorAndSourceResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeGroupCoordinatorAndSource",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeGroupCoordinatorAndSource: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeGroupCoordinatorAndSource == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.BecomeGroupCoordinatorAndSource()`)
	}

	return r.Body.BecomeGroupCoordinatorAndSource, nil
}

type ChangeCoordinatorArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	NewCoordinator        string `xml:"NewCoordinator"`
	NewTransportSettings  string `xml:"NewTransportSettings"`
	CurrentAVTransportURI string `xml:"CurrentAVTransportURI"`
}
type ChangeCoordinatorResponse struct {
}

func (s *Service) ChangeCoordinator(args *ChangeCoordinatorArgs) (*ChangeCoordinatorResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ChangeCoordinator",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ChangeCoordinator: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ChangeCoordinator == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.ChangeCoordinator()`)
	}

	return r.Body.ChangeCoordinator, nil
}

type ChangeTransportSettingsArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	NewTransportSettings  string `xml:"NewTransportSettings"`
	CurrentAVTransportURI string `xml:"CurrentAVTransportURI"`
}
type ChangeTransportSettingsResponse struct {
}

func (s *Service) ChangeTransportSettings(args *ChangeTransportSettingsArgs) (*ChangeTransportSettingsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ChangeTransportSettings",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ChangeTransportSettings: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ChangeTransportSettings == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.ChangeTransportSettings()`)
	}

	return r.Body.ChangeTransportSettings, nil
}

type ConfigureSleepTimerArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	NewSleepTimerDuration string `xml:"NewSleepTimerDuration"`
}
type ConfigureSleepTimerResponse struct {
}

func (s *Service) ConfigureSleepTimer(args *ConfigureSleepTimerArgs) (*ConfigureSleepTimerResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ConfigureSleepTimer",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ConfigureSleepTimer: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ConfigureSleepTimer == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.ConfigureSleepTimer()`)
	}

	return r.Body.ConfigureSleepTimer, nil
}

type GetRemainingSleepTimerDurationArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetRemainingSleepTimerDurationResponse struct {
	RemainingSleepTimerDuration string `xml:"RemainingSleepTimerDuration"`
	CurrentSleepTimerGeneration uint32 `xml:"CurrentSleepTimerGeneration"`
}

func (s *Service) GetRemainingSleepTimerDuration(args *GetRemainingSleepTimerDurationArgs) (*GetRemainingSleepTimerDurationResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRemainingSleepTimerDuration",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRemainingSleepTimerDuration: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRemainingSleepTimerDuration == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetRemainingSleepTimerDuration()`)
	}

	return r.Body.GetRemainingSleepTimerDuration, nil
}

type RunAlarmArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	AlarmID         uint32 `xml:"AlarmID"`
	LoggedStartTime string `xml:"LoggedStartTime"`
	Duration        string `xml:"Duration"`
	ProgramURI      string `xml:"ProgramURI"`
	ProgramMetaData string `xml:"ProgramMetaData"`
	// Allowed Value: NORMAL
	// Allowed Value: REPEAT_ALL
	// Allowed Value: REPEAT_ONE
	// Allowed Value: SHUFFLE_NOREPEAT
	// Allowed Value: SHUFFLE
	// Allowed Value: SHUFFLE_REPEAT_ONE
	PlayMode           string `xml:"PlayMode"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
}
type RunAlarmResponse struct {
}

func (s *Service) RunAlarm(args *RunAlarmArgs) (*RunAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RunAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RunAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RunAlarm == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.RunAlarm()`)
	}

	return r.Body.RunAlarm, nil
}

type StartAutoplayArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	InstanceID         uint32 `xml:"InstanceID"`
	ProgramURI         string `xml:"ProgramURI"`
	ProgramMetaData    string `xml:"ProgramMetaData"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
	ResetVolumeAfter   bool   `xml:"ResetVolumeAfter"`
}
type StartAutoplayResponse struct {
}

func (s *Service) StartAutoplay(args *StartAutoplayArgs) (*StartAutoplayResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("StartAutoplay",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{StartAutoplay: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.StartAutoplay == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.StartAutoplay()`)
	}

	return r.Body.StartAutoplay, nil
}

type GetRunningAlarmPropertiesArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type GetRunningAlarmPropertiesResponse struct {
	AlarmID         uint32 `xml:"AlarmID"`
	GroupID         string `xml:"GroupID"`
	LoggedStartTime string `xml:"LoggedStartTime"`
}

func (s *Service) GetRunningAlarmProperties(args *GetRunningAlarmPropertiesArgs) (*GetRunningAlarmPropertiesResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRunningAlarmProperties",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRunningAlarmProperties: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRunningAlarmProperties == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.GetRunningAlarmProperties()`)
	}

	return r.Body.GetRunningAlarmProperties, nil
}

type SnoozeAlarmArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Duration   string `xml:"Duration"`
}
type SnoozeAlarmResponse struct {
}

func (s *Service) SnoozeAlarm(args *SnoozeAlarmArgs) (*SnoozeAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SnoozeAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SnoozeAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SnoozeAlarm == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.SnoozeAlarm()`)
	}

	return r.Body.SnoozeAlarm, nil
}

type EndDirectControlSessionArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}
type EndDirectControlSessionResponse struct {
}

func (s *Service) EndDirectControlSession(args *EndDirectControlSessionArgs) (*EndDirectControlSessionResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("EndDirectControlSession",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{EndDirectControlSession: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.EndDirectControlSession == nil {
		return nil, errors.New(`unexpected response from service calling avtransport.EndDirectControlSession()`)
	}

	return r.Body.EndDirectControlSession, nil
}

type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}
type Property struct {
	XMLName    xml.Name    `xml:"property"`
	LastChange *LastChange `xml:"LastChange"`
}

func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}
	err := xml.Unmarshal(body, &evt)
	if err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.LastChange != nil:
			zp.LastChange = prop.LastChange
			events = append(events, *prop.LastChange)
		}
	}
	return events
}
