// Code generated by makeservice. DO NOT EDIT.

// Package alarmclock is a generated AlarmClock package.
package alarmclock

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io/ioutil"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:AlarmClock:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

type TimeZone string
type TimeServer string
type TimeGeneration uint32
type AlarmListVersion string
type DailyIndexRefreshTime string
type TimeFormat string
type DateFormat string

type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL

	TimeZone              *TimeZone
	TimeServer            *TimeServer
	TimeGeneration        *TimeGeneration
	AlarmListVersion      *AlarmListVersion
	DailyIndexRefreshTime *DailyIndexRefreshTime
	TimeFormat            *TimeFormat
	DateFormat            *DateFormat

	location *url.URL
	client   *http.Client
}

func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/AlarmClock/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/AlarmClock/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

func (s *Service) Location() *url.URL {
	return s.location
}

func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                  xml.Name                      `xml:"s:Body"`
	SetFormat                *SetFormatArgs                `xml:"u:SetFormat,omitempty"`
	GetFormat                *GetFormatArgs                `xml:"u:GetFormat,omitempty"`
	SetTimeZone              *SetTimeZoneArgs              `xml:"u:SetTimeZone,omitempty"`
	GetTimeZone              *GetTimeZoneArgs              `xml:"u:GetTimeZone,omitempty"`
	GetTimeZoneAndRule       *GetTimeZoneAndRuleArgs       `xml:"u:GetTimeZoneAndRule,omitempty"`
	GetTimeZoneRule          *GetTimeZoneRuleArgs          `xml:"u:GetTimeZoneRule,omitempty"`
	SetTimeServer            *SetTimeServerArgs            `xml:"u:SetTimeServer,omitempty"`
	GetTimeServer            *GetTimeServerArgs            `xml:"u:GetTimeServer,omitempty"`
	SetTimeNow               *SetTimeNowArgs               `xml:"u:SetTimeNow,omitempty"`
	GetHouseholdTimeAtStamp  *GetHouseholdTimeAtStampArgs  `xml:"u:GetHouseholdTimeAtStamp,omitempty"`
	GetTimeNow               *GetTimeNowArgs               `xml:"u:GetTimeNow,omitempty"`
	CreateAlarm              *CreateAlarmArgs              `xml:"u:CreateAlarm,omitempty"`
	UpdateAlarm              *UpdateAlarmArgs              `xml:"u:UpdateAlarm,omitempty"`
	DestroyAlarm             *DestroyAlarmArgs             `xml:"u:DestroyAlarm,omitempty"`
	ListAlarms               *ListAlarmsArgs               `xml:"u:ListAlarms,omitempty"`
	SetDailyIndexRefreshTime *SetDailyIndexRefreshTimeArgs `xml:"u:SetDailyIndexRefreshTime,omitempty"`
	GetDailyIndexRefreshTime *GetDailyIndexRefreshTimeArgs `xml:"u:GetDailyIndexRefreshTime,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                  xml.Name                          `xml:"Body"`
	SetFormat                *SetFormatResponse                `xml:"SetFormatResponse,omitempty"`
	GetFormat                *GetFormatResponse                `xml:"GetFormatResponse,omitempty"`
	SetTimeZone              *SetTimeZoneResponse              `xml:"SetTimeZoneResponse,omitempty"`
	GetTimeZone              *GetTimeZoneResponse              `xml:"GetTimeZoneResponse,omitempty"`
	GetTimeZoneAndRule       *GetTimeZoneAndRuleResponse       `xml:"GetTimeZoneAndRuleResponse,omitempty"`
	GetTimeZoneRule          *GetTimeZoneRuleResponse          `xml:"GetTimeZoneRuleResponse,omitempty"`
	SetTimeServer            *SetTimeServerResponse            `xml:"SetTimeServerResponse,omitempty"`
	GetTimeServer            *GetTimeServerResponse            `xml:"GetTimeServerResponse,omitempty"`
	SetTimeNow               *SetTimeNowResponse               `xml:"SetTimeNowResponse,omitempty"`
	GetHouseholdTimeAtStamp  *GetHouseholdTimeAtStampResponse  `xml:"GetHouseholdTimeAtStampResponse,omitempty"`
	GetTimeNow               *GetTimeNowResponse               `xml:"GetTimeNowResponse,omitempty"`
	CreateAlarm              *CreateAlarmResponse              `xml:"CreateAlarmResponse,omitempty"`
	UpdateAlarm              *UpdateAlarmResponse              `xml:"UpdateAlarmResponse,omitempty"`
	DestroyAlarm             *DestroyAlarmResponse             `xml:"DestroyAlarmResponse,omitempty"`
	ListAlarms               *ListAlarmsResponse               `xml:"ListAlarmsResponse,omitempty"`
	SetDailyIndexRefreshTime *SetDailyIndexRefreshTimeResponse `xml:"SetDailyIndexRefreshTimeResponse,omitempty"`
	GetDailyIndexRefreshTime *GetDailyIndexRefreshTimeResponse `xml:"GetDailyIndexRefreshTimeResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

type SetFormatArgs struct {
	Xmlns             string `xml:"xmlns:u,attr"`
	DesiredTimeFormat string `xml:"DesiredTimeFormat"`
	DesiredDateFormat string `xml:"DesiredDateFormat"`
}
type SetFormatResponse struct {
}

func (s *Service) SetFormat(args *SetFormatArgs) (*SetFormatResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetFormat",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetFormat: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetFormat == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.SetFormat()`)
	}

	return r.Body.SetFormat, nil
}

type GetFormatArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetFormatResponse struct {
	CurrentTimeFormat string `xml:"CurrentTimeFormat"`
	CurrentDateFormat string `xml:"CurrentDateFormat"`
}

func (s *Service) GetFormat(args *GetFormatArgs) (*GetFormatResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetFormat",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetFormat: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetFormat == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetFormat()`)
	}

	return r.Body.GetFormat, nil
}

type SetTimeZoneArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	Index         int32  `xml:"Index"`
	AutoAdjustDst bool   `xml:"AutoAdjustDst"`
}
type SetTimeZoneResponse struct {
}

func (s *Service) SetTimeZone(args *SetTimeZoneArgs) (*SetTimeZoneResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetTimeZone",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetTimeZone: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetTimeZone == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.SetTimeZone()`)
	}

	return r.Body.SetTimeZone, nil
}

type GetTimeZoneArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetTimeZoneResponse struct {
	Index         int32 `xml:"Index"`
	AutoAdjustDst bool  `xml:"AutoAdjustDst"`
}

func (s *Service) GetTimeZone(args *GetTimeZoneArgs) (*GetTimeZoneResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTimeZone",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTimeZone: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTimeZone == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetTimeZone()`)
	}

	return r.Body.GetTimeZone, nil
}

type GetTimeZoneAndRuleArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetTimeZoneAndRuleResponse struct {
	Index           int32  `xml:"Index"`
	AutoAdjustDst   bool   `xml:"AutoAdjustDst"`
	CurrentTimeZone string `xml:"CurrentTimeZone"`
}

func (s *Service) GetTimeZoneAndRule(args *GetTimeZoneAndRuleArgs) (*GetTimeZoneAndRuleResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTimeZoneAndRule",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTimeZoneAndRule: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTimeZoneAndRule == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetTimeZoneAndRule()`)
	}

	return r.Body.GetTimeZoneAndRule, nil
}

type GetTimeZoneRuleArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
	Index int32  `xml:"Index"`
}
type GetTimeZoneRuleResponse struct {
	TimeZone string `xml:"TimeZone"`
}

func (s *Service) GetTimeZoneRule(args *GetTimeZoneRuleArgs) (*GetTimeZoneRuleResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTimeZoneRule",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTimeZoneRule: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTimeZoneRule == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetTimeZoneRule()`)
	}

	return r.Body.GetTimeZoneRule, nil
}

type SetTimeServerArgs struct {
	Xmlns             string `xml:"xmlns:u,attr"`
	DesiredTimeServer string `xml:"DesiredTimeServer"`
}
type SetTimeServerResponse struct {
}

func (s *Service) SetTimeServer(args *SetTimeServerArgs) (*SetTimeServerResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetTimeServer",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetTimeServer: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetTimeServer == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.SetTimeServer()`)
	}

	return r.Body.SetTimeServer, nil
}

type GetTimeServerArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetTimeServerResponse struct {
	CurrentTimeServer string `xml:"CurrentTimeServer"`
}

func (s *Service) GetTimeServer(args *GetTimeServerArgs) (*GetTimeServerResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTimeServer",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTimeServer: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTimeServer == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetTimeServer()`)
	}

	return r.Body.GetTimeServer, nil
}

type SetTimeNowArgs struct {
	Xmlns                  string `xml:"xmlns:u,attr"`
	DesiredTime            string `xml:"DesiredTime"`
	TimeZoneForDesiredTime string `xml:"TimeZoneForDesiredTime"`
}
type SetTimeNowResponse struct {
}

func (s *Service) SetTimeNow(args *SetTimeNowArgs) (*SetTimeNowResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetTimeNow",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetTimeNow: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetTimeNow == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.SetTimeNow()`)
	}

	return r.Body.SetTimeNow, nil
}

type GetHouseholdTimeAtStampArgs struct {
	Xmlns     string `xml:"xmlns:u,attr"`
	TimeStamp string `xml:"TimeStamp"`
}
type GetHouseholdTimeAtStampResponse struct {
	HouseholdUTCTime string `xml:"HouseholdUTCTime"`
}

func (s *Service) GetHouseholdTimeAtStamp(args *GetHouseholdTimeAtStampArgs) (*GetHouseholdTimeAtStampResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetHouseholdTimeAtStamp",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetHouseholdTimeAtStamp: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetHouseholdTimeAtStamp == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetHouseholdTimeAtStamp()`)
	}

	return r.Body.GetHouseholdTimeAtStamp, nil
}

type GetTimeNowArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetTimeNowResponse struct {
	CurrentUTCTime        string `xml:"CurrentUTCTime"`
	CurrentLocalTime      string `xml:"CurrentLocalTime"`
	CurrentTimeZone       string `xml:"CurrentTimeZone"`
	CurrentTimeGeneration uint32 `xml:"CurrentTimeGeneration"`
}

func (s *Service) GetTimeNow(args *GetTimeNowArgs) (*GetTimeNowResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTimeNow",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTimeNow: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTimeNow == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetTimeNow()`)
	}

	return r.Body.GetTimeNow, nil
}

type CreateAlarmArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	StartLocalTime string `xml:"StartLocalTime"`
	Duration       string `xml:"Duration"`
	// Allowed Value: ONCE
	// Allowed Value: WEEKDAYS
	// Allowed Value: WEEKENDS
	// Allowed Value: DAILY
	Recurrence      string `xml:"Recurrence"`
	Enabled         bool   `xml:"Enabled"`
	RoomUUID        string `xml:"RoomUUID"`
	ProgramURI      string `xml:"ProgramURI"`
	ProgramMetaData string `xml:"ProgramMetaData"`
	// Allowed Value: NORMAL
	// Allowed Value: REPEAT_ALL
	// Allowed Value: SHUFFLE_NOREPEAT
	// Allowed Value: SHUFFLE
	PlayMode           string `xml:"PlayMode"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
}
type CreateAlarmResponse struct {
	AssignedID uint32 `xml:"AssignedID"`
}

func (s *Service) CreateAlarm(args *CreateAlarmArgs) (*CreateAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("CreateAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{CreateAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.CreateAlarm == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.CreateAlarm()`)
	}

	return r.Body.CreateAlarm, nil
}

type UpdateAlarmArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	ID             uint32 `xml:"ID"`
	StartLocalTime string `xml:"StartLocalTime"`
	Duration       string `xml:"Duration"`
	// Allowed Value: ONCE
	// Allowed Value: WEEKDAYS
	// Allowed Value: WEEKENDS
	// Allowed Value: DAILY
	Recurrence      string `xml:"Recurrence"`
	Enabled         bool   `xml:"Enabled"`
	RoomUUID        string `xml:"RoomUUID"`
	ProgramURI      string `xml:"ProgramURI"`
	ProgramMetaData string `xml:"ProgramMetaData"`
	// Allowed Value: NORMAL
	// Allowed Value: REPEAT_ALL
	// Allowed Value: SHUFFLE_NOREPEAT
	// Allowed Value: SHUFFLE
	PlayMode           string `xml:"PlayMode"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
}
type UpdateAlarmResponse struct {
}

func (s *Service) UpdateAlarm(args *UpdateAlarmArgs) (*UpdateAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("UpdateAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{UpdateAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.UpdateAlarm == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.UpdateAlarm()`)
	}

	return r.Body.UpdateAlarm, nil
}

type DestroyAlarmArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
	ID    uint32 `xml:"ID"`
}
type DestroyAlarmResponse struct {
}

func (s *Service) DestroyAlarm(args *DestroyAlarmArgs) (*DestroyAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("DestroyAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{DestroyAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.DestroyAlarm == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.DestroyAlarm()`)
	}

	return r.Body.DestroyAlarm, nil
}

type ListAlarmsArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type ListAlarmsResponse struct {
	CurrentAlarmList        string `xml:"CurrentAlarmList"`
	CurrentAlarmListVersion string `xml:"CurrentAlarmListVersion"`
}

func (s *Service) ListAlarms(args *ListAlarmsArgs) (*ListAlarmsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ListAlarms",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ListAlarms: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ListAlarms == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.ListAlarms()`)
	}

	return r.Body.ListAlarms, nil
}

type SetDailyIndexRefreshTimeArgs struct {
	Xmlns                        string `xml:"xmlns:u,attr"`
	DesiredDailyIndexRefreshTime string `xml:"DesiredDailyIndexRefreshTime"`
}
type SetDailyIndexRefreshTimeResponse struct {
}

func (s *Service) SetDailyIndexRefreshTime(args *SetDailyIndexRefreshTimeArgs) (*SetDailyIndexRefreshTimeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetDailyIndexRefreshTime",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetDailyIndexRefreshTime: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetDailyIndexRefreshTime == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.SetDailyIndexRefreshTime()`)
	}

	return r.Body.SetDailyIndexRefreshTime, nil
}

type GetDailyIndexRefreshTimeArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetDailyIndexRefreshTimeResponse struct {
	CurrentDailyIndexRefreshTime string `xml:"CurrentDailyIndexRefreshTime"`
}

func (s *Service) GetDailyIndexRefreshTime(args *GetDailyIndexRefreshTimeArgs) (*GetDailyIndexRefreshTimeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetDailyIndexRefreshTime",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetDailyIndexRefreshTime: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetDailyIndexRefreshTime == nil {
		return nil, errors.New(`unexpected response from service calling alarmclock.GetDailyIndexRefreshTime()`)
	}

	return r.Body.GetDailyIndexRefreshTime, nil
}

type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}
type Property struct {
	XMLName               xml.Name               `xml:"property"`
	TimeZone              *TimeZone              `xml:"TimeZone"`
	TimeServer            *TimeServer            `xml:"TimeServer"`
	TimeGeneration        *TimeGeneration        `xml:"TimeGeneration"`
	AlarmListVersion      *AlarmListVersion      `xml:"AlarmListVersion"`
	DailyIndexRefreshTime *DailyIndexRefreshTime `xml:"DailyIndexRefreshTime"`
	TimeFormat            *TimeFormat            `xml:"TimeFormat"`
	DateFormat            *DateFormat            `xml:"DateFormat"`
}

func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}
	err := xml.Unmarshal(body, &evt)
	if err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.TimeZone != nil:
			zp.TimeZone = prop.TimeZone
			events = append(events, *prop.TimeZone)
		case prop.TimeServer != nil:
			zp.TimeServer = prop.TimeServer
			events = append(events, *prop.TimeServer)
		case prop.TimeGeneration != nil:
			zp.TimeGeneration = prop.TimeGeneration
			events = append(events, *prop.TimeGeneration)
		case prop.AlarmListVersion != nil:
			zp.AlarmListVersion = prop.AlarmListVersion
			events = append(events, *prop.AlarmListVersion)
		case prop.DailyIndexRefreshTime != nil:
			zp.DailyIndexRefreshTime = prop.DailyIndexRefreshTime
			events = append(events, *prop.DailyIndexRefreshTime)
		case prop.TimeFormat != nil:
			zp.TimeFormat = prop.TimeFormat
			events = append(events, *prop.TimeFormat)
		case prop.DateFormat != nil:
			zp.DateFormat = prop.DateFormat
			events = append(events, *prop.DateFormat)
		}
	}
	return events
}
