// Code generated by makeservice. DO NOT EDIT.

// Package systemproperties is a generated SystemProperties package.
package systemproperties

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io/ioutil"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:SystemProperties:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

type CustomerID string
type UpdateID uint32
type UpdateIDX uint32
type VoiceUpdateID uint32
type ThirdPartyHash string

type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL

	CustomerID     *CustomerID
	UpdateID       *UpdateID
	UpdateIDX      *UpdateIDX
	VoiceUpdateID  *VoiceUpdateID
	ThirdPartyHash *ThirdPartyHash

	location *url.URL
	client   *http.Client
}

func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/SystemProperties/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/SystemProperties/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

func (s *Service) Location() *url.URL {
	return s.location
}

func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                            xml.Name                                `xml:"s:Body"`
	SetString                          *SetStringArgs                          `xml:"u:SetString,omitempty"`
	GetString                          *GetStringArgs                          `xml:"u:GetString,omitempty"`
	Remove                             *RemoveArgs                             `xml:"u:Remove,omitempty"`
	GetWebCode                         *GetWebCodeArgs                         `xml:"u:GetWebCode,omitempty"`
	ProvisionCredentialedTrialAccountX *ProvisionCredentialedTrialAccountXArgs `xml:"u:ProvisionCredentialedTrialAccountX,omitempty"`
	AddAccountX                        *AddAccountXArgs                        `xml:"u:AddAccountX,omitempty"`
	AddOAuthAccountX                   *AddOAuthAccountXArgs                   `xml:"u:AddOAuthAccountX,omitempty"`
	RemoveAccount                      *RemoveAccountArgs                      `xml:"u:RemoveAccount,omitempty"`
	EditAccountPasswordX               *EditAccountPasswordXArgs               `xml:"u:EditAccountPasswordX,omitempty"`
	SetAccountNicknameX                *SetAccountNicknameXArgs                `xml:"u:SetAccountNicknameX,omitempty"`
	RefreshAccountCredentialsX         *RefreshAccountCredentialsXArgs         `xml:"u:RefreshAccountCredentialsX,omitempty"`
	EditAccountMd                      *EditAccountMdArgs                      `xml:"u:EditAccountMd,omitempty"`
	DoPostUpdateTasks                  *DoPostUpdateTasksArgs                  `xml:"u:DoPostUpdateTasks,omitempty"`
	ResetThirdPartyCredentials         *ResetThirdPartyCredentialsArgs         `xml:"u:ResetThirdPartyCredentials,omitempty"`
	EnableRDM                          *EnableRDMArgs                          `xml:"u:EnableRDM,omitempty"`
	GetRDM                             *GetRDMArgs                             `xml:"u:GetRDM,omitempty"`
	ReplaceAccountX                    *ReplaceAccountXArgs                    `xml:"u:ReplaceAccountX,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                            xml.Name                                    `xml:"Body"`
	SetString                          *SetStringResponse                          `xml:"SetStringResponse,omitempty"`
	GetString                          *GetStringResponse                          `xml:"GetStringResponse,omitempty"`
	Remove                             *RemoveResponse                             `xml:"RemoveResponse,omitempty"`
	GetWebCode                         *GetWebCodeResponse                         `xml:"GetWebCodeResponse,omitempty"`
	ProvisionCredentialedTrialAccountX *ProvisionCredentialedTrialAccountXResponse `xml:"ProvisionCredentialedTrialAccountXResponse,omitempty"`
	AddAccountX                        *AddAccountXResponse                        `xml:"AddAccountXResponse,omitempty"`
	AddOAuthAccountX                   *AddOAuthAccountXResponse                   `xml:"AddOAuthAccountXResponse,omitempty"`
	RemoveAccount                      *RemoveAccountResponse                      `xml:"RemoveAccountResponse,omitempty"`
	EditAccountPasswordX               *EditAccountPasswordXResponse               `xml:"EditAccountPasswordXResponse,omitempty"`
	SetAccountNicknameX                *SetAccountNicknameXResponse                `xml:"SetAccountNicknameXResponse,omitempty"`
	RefreshAccountCredentialsX         *RefreshAccountCredentialsXResponse         `xml:"RefreshAccountCredentialsXResponse,omitempty"`
	EditAccountMd                      *EditAccountMdResponse                      `xml:"EditAccountMdResponse,omitempty"`
	DoPostUpdateTasks                  *DoPostUpdateTasksResponse                  `xml:"DoPostUpdateTasksResponse,omitempty"`
	ResetThirdPartyCredentials         *ResetThirdPartyCredentialsResponse         `xml:"ResetThirdPartyCredentialsResponse,omitempty"`
	EnableRDM                          *EnableRDMResponse                          `xml:"EnableRDMResponse,omitempty"`
	GetRDM                             *GetRDMResponse                             `xml:"GetRDMResponse,omitempty"`
	ReplaceAccountX                    *ReplaceAccountXResponse                    `xml:"ReplaceAccountXResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

type SetStringArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	VariableName string `xml:"VariableName"`
	StringValue  string `xml:"StringValue"`
}
type SetStringResponse struct {
}

func (s *Service) SetString(args *SetStringArgs) (*SetStringResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetString",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetString: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetString == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.SetString()`)
	}

	return r.Body.SetString, nil
}

type GetStringArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	VariableName string `xml:"VariableName"`
}
type GetStringResponse struct {
	StringValue string `xml:"StringValue"`
}

func (s *Service) GetString(args *GetStringArgs) (*GetStringResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetString",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetString: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetString == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.GetString()`)
	}

	return r.Body.GetString, nil
}

type RemoveArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	VariableName string `xml:"VariableName"`
}
type RemoveResponse struct {
}

func (s *Service) Remove(args *RemoveArgs) (*RemoveResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Remove",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Remove: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Remove == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.Remove()`)
	}

	return r.Body.Remove, nil
}

type GetWebCodeArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	AccountType uint32 `xml:"AccountType"`
}
type GetWebCodeResponse struct {
	WebCode string `xml:"WebCode"`
}

func (s *Service) GetWebCode(args *GetWebCodeArgs) (*GetWebCodeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetWebCode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetWebCode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetWebCode == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.GetWebCode()`)
	}

	return r.Body.GetWebCode, nil
}

type ProvisionCredentialedTrialAccountXArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	AccountType     uint32 `xml:"AccountType"`
	AccountID       string `xml:"AccountID"`
	AccountPassword string `xml:"AccountPassword"`
}
type ProvisionCredentialedTrialAccountXResponse struct {
	IsExpired  bool   `xml:"IsExpired"`
	AccountUDN string `xml:"AccountUDN"`
}

func (s *Service) ProvisionCredentialedTrialAccountX(args *ProvisionCredentialedTrialAccountXArgs) (*ProvisionCredentialedTrialAccountXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ProvisionCredentialedTrialAccountX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ProvisionCredentialedTrialAccountX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ProvisionCredentialedTrialAccountX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.ProvisionCredentialedTrialAccountX()`)
	}

	return r.Body.ProvisionCredentialedTrialAccountX, nil
}

type AddAccountXArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	AccountType     uint32 `xml:"AccountType"`
	AccountID       string `xml:"AccountID"`
	AccountPassword string `xml:"AccountPassword"`
}
type AddAccountXResponse struct {
	AccountUDN string `xml:"AccountUDN"`
}

func (s *Service) AddAccountX(args *AddAccountXArgs) (*AddAccountXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddAccountX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddAccountX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddAccountX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.AddAccountX()`)
	}

	return r.Body.AddAccountX, nil
}

type AddOAuthAccountXArgs struct {
	Xmlns             string `xml:"xmlns:u,attr"`
	AccountType       uint32 `xml:"AccountType"`
	AccountToken      string `xml:"AccountToken"`
	AccountKey        string `xml:"AccountKey"`
	OAuthDeviceID     string `xml:"OAuthDeviceID"`
	AuthorizationCode string `xml:"AuthorizationCode"`
	RedirectURI       string `xml:"RedirectURI"`
	UserIdHashCode    string `xml:"UserIdHashCode"`
	AccountTier       uint32 `xml:"AccountTier"`
}
type AddOAuthAccountXResponse struct {
	AccountUDN      string `xml:"AccountUDN"`
	AccountNickname string `xml:"AccountNickname"`
}

func (s *Service) AddOAuthAccountX(args *AddOAuthAccountXArgs) (*AddOAuthAccountXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddOAuthAccountX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddOAuthAccountX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddOAuthAccountX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.AddOAuthAccountX()`)
	}

	return r.Body.AddOAuthAccountX, nil
}

type RemoveAccountArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	AccountType uint32 `xml:"AccountType"`
	AccountID   string `xml:"AccountID"`
}
type RemoveAccountResponse struct {
}

func (s *Service) RemoveAccount(args *RemoveAccountArgs) (*RemoveAccountResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveAccount",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveAccount: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveAccount == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.RemoveAccount()`)
	}

	return r.Body.RemoveAccount, nil
}

type EditAccountPasswordXArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	AccountType        uint32 `xml:"AccountType"`
	AccountID          string `xml:"AccountID"`
	NewAccountPassword string `xml:"NewAccountPassword"`
}
type EditAccountPasswordXResponse struct {
}

func (s *Service) EditAccountPasswordX(args *EditAccountPasswordXArgs) (*EditAccountPasswordXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("EditAccountPasswordX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{EditAccountPasswordX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.EditAccountPasswordX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.EditAccountPasswordX()`)
	}

	return r.Body.EditAccountPasswordX, nil
}

type SetAccountNicknameXArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	AccountUDN      string `xml:"AccountUDN"`
	AccountNickname string `xml:"AccountNickname"`
}
type SetAccountNicknameXResponse struct {
}

func (s *Service) SetAccountNicknameX(args *SetAccountNicknameXArgs) (*SetAccountNicknameXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetAccountNicknameX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetAccountNicknameX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetAccountNicknameX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.SetAccountNicknameX()`)
	}

	return r.Body.SetAccountNicknameX, nil
}

type RefreshAccountCredentialsXArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	AccountType  uint32 `xml:"AccountType"`
	AccountUID   uint32 `xml:"AccountUID"`
	AccountToken string `xml:"AccountToken"`
	AccountKey   string `xml:"AccountKey"`
}
type RefreshAccountCredentialsXResponse struct {
}

func (s *Service) RefreshAccountCredentialsX(args *RefreshAccountCredentialsXArgs) (*RefreshAccountCredentialsXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RefreshAccountCredentialsX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RefreshAccountCredentialsX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RefreshAccountCredentialsX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.RefreshAccountCredentialsX()`)
	}

	return r.Body.RefreshAccountCredentialsX, nil
}

type EditAccountMdArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	AccountType  uint32 `xml:"AccountType"`
	AccountID    string `xml:"AccountID"`
	NewAccountMd string `xml:"NewAccountMd"`
}
type EditAccountMdResponse struct {
}

func (s *Service) EditAccountMd(args *EditAccountMdArgs) (*EditAccountMdResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("EditAccountMd",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{EditAccountMd: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.EditAccountMd == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.EditAccountMd()`)
	}

	return r.Body.EditAccountMd, nil
}

type DoPostUpdateTasksArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type DoPostUpdateTasksResponse struct {
}

func (s *Service) DoPostUpdateTasks(args *DoPostUpdateTasksArgs) (*DoPostUpdateTasksResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("DoPostUpdateTasks",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{DoPostUpdateTasks: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.DoPostUpdateTasks == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.DoPostUpdateTasks()`)
	}

	return r.Body.DoPostUpdateTasks, nil
}

type ResetThirdPartyCredentialsArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type ResetThirdPartyCredentialsResponse struct {
}

func (s *Service) ResetThirdPartyCredentials(args *ResetThirdPartyCredentialsArgs) (*ResetThirdPartyCredentialsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ResetThirdPartyCredentials",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ResetThirdPartyCredentials: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ResetThirdPartyCredentials == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.ResetThirdPartyCredentials()`)
	}

	return r.Body.ResetThirdPartyCredentials, nil
}

type EnableRDMArgs struct {
	Xmlns    string `xml:"xmlns:u,attr"`
	RDMValue bool   `xml:"RDMValue"`
}
type EnableRDMResponse struct {
}

func (s *Service) EnableRDM(args *EnableRDMArgs) (*EnableRDMResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("EnableRDM",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{EnableRDM: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.EnableRDM == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.EnableRDM()`)
	}

	return r.Body.EnableRDM, nil
}

type GetRDMArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}
type GetRDMResponse struct {
	RDMValue bool `xml:"RDMValue"`
}

func (s *Service) GetRDM(args *GetRDMArgs) (*GetRDMResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRDM",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRDM: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRDM == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.GetRDM()`)
	}

	return r.Body.GetRDM, nil
}

type ReplaceAccountXArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	AccountUDN         string `xml:"AccountUDN"`
	NewAccountID       string `xml:"NewAccountID"`
	NewAccountPassword string `xml:"NewAccountPassword"`
	AccountToken       string `xml:"AccountToken"`
	AccountKey         string `xml:"AccountKey"`
	OAuthDeviceID      string `xml:"OAuthDeviceID"`
}
type ReplaceAccountXResponse struct {
	NewAccountUDN string `xml:"NewAccountUDN"`
}

func (s *Service) ReplaceAccountX(args *ReplaceAccountXArgs) (*ReplaceAccountXResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ReplaceAccountX",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ReplaceAccountX: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ReplaceAccountX == nil {
		return nil, errors.New(`unexpected response from service calling systemproperties.ReplaceAccountX()`)
	}

	return r.Body.ReplaceAccountX, nil
}

type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}
type Property struct {
	XMLName        xml.Name        `xml:"property"`
	CustomerID     *CustomerID     `xml:"CustomerID"`
	UpdateID       *UpdateID       `xml:"UpdateID"`
	UpdateIDX      *UpdateIDX      `xml:"UpdateIDX"`
	VoiceUpdateID  *VoiceUpdateID  `xml:"VoiceUpdateID"`
	ThirdPartyHash *ThirdPartyHash `xml:"ThirdPartyHash"`
}

func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}
	err := xml.Unmarshal(body, &evt)
	if err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.CustomerID != nil:
			zp.CustomerID = prop.CustomerID
			events = append(events, *prop.CustomerID)
		case prop.UpdateID != nil:
			zp.UpdateID = prop.UpdateID
			events = append(events, *prop.UpdateID)
		case prop.UpdateIDX != nil:
			zp.UpdateIDX = prop.UpdateIDX
			events = append(events, *prop.UpdateIDX)
		case prop.VoiceUpdateID != nil:
			zp.VoiceUpdateID = prop.VoiceUpdateID
			events = append(events, *prop.VoiceUpdateID)
		case prop.ThirdPartyHash != nil:
			zp.ThirdPartyHash = prop.ThirdPartyHash
			events = append(events, *prop.ThirdPartyHash)
		}
	}
	return events
}
